apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    app: nginx-rc
  template:
    metadata:
      labels:
        app: nginx-rc
    spec:
      nodeSelector:
        role: nginx-rc
      containers:
      - name: nginx
        image: nginx
        ports:
          - name: http
            containerPort: 80
            hostPort: 80
        volumeMounts:
          - mountPath: "/data"
            name: data-nginx
      volumes:
        - hostPath:
            path: "/data"
          name: data-nginx
